---
title: "final_proj"
author: "Mary Ardoin & Lauren Fowler"
date: "4/11/2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Final Project

```{r loading in my data, echo = FALSE}
library(tidyverse)
library(psych)
library(naniar)
library(Hmisc)
library(naniar)
library(skimr)
library(correlation)
dirty_data <- read_csv("~/ds/final_project/vax_hes.csv")
#dirty_data <- read_csv("~/ds/final_project/vax_hes.csv")
view(dirty_data)
```

```{r renaming}
names(dirty_data)[names(dirty_data) == "Estimated hesitant"] <- "hes"
names(dirty_data)[names(dirty_data) == "State"] <- "state"
names(dirty_data)[names(dirty_data) == "Percent non-Hispanic White"] <- "white" 
names(dirty_data)[names(dirty_data) == "Percent Hispanic"] <- "his" 
names(dirty_data)[names(dirty_data) == "Percent non-Hispanic Black"] <- "black" 
names(dirty_data)[names(dirty_data) == "Percent non-Hispanic American Indian/Alaska Native"] <- "AI" 
names(dirty_data)[names(dirty_data) == "Percent non-Hispanic Asian"] <- "asian" 
names(dirty_data)[names(dirty_data) == "Percent non-Hispanic Native Hawaiian/Pacific Islander"] <- "haw" 
names(dirty_data)[names(dirty_data) == "Percent adults fully vaccinated against COVID-19 (as of 6/10/21)"] <- "full_vac" 
names(dirty_data)[names(dirty_data) == "CVAC level of concern for vaccination rollout"] <- "concern" 
names(dirty_data)[names(dirty_data) == "string_hes"] <- "strong_hes" 
view(dirty_data)

```

```{r making the data smaller}
colnames(dirty_data)

small_data <- select(dirty_data, state, hes, white, his, black, concern, AI, asian, haw, full_vac)
view(small_data)
```

```{r trying to group the data}

group_data <- small_data %>%
 group_by(state) %>%
 summarise(mean_hes = mean(hes), mean_white = mean(white), mean_his = mean(his), mean_black = mean(black), mean_concern = mean(concern), mean_AI = mean(AI), mean_asian = mean(asian), mean_haw = mean(haw), mean_full_vac = mean(full_vac))

view(group_data)
```

```{r saving the file}
write_csv(group_data, "~/ds/final_project/final_2.csv")
```

```{r running the regression white}
library(jtools)
glimpse(group_data)

group_data <- mutate(group_data, state = as.factor(state))
#to run the analysis without making it its own object and only having the beta coefficients 
lm(mean_strong_hes ~ mean_white, group_data)
# to have more details on the full test create a new object using the "=" symbol
lmhes = lm(mean_strong_hes ~ mean_white, group_data)
summary(lmhes)
plot(lmhes)
summ(lmhes)
skim(group_data)
```

```{r LR his}
#to run the analysis without making it its own object and only having the beta coefficients 
lm(mean_hes ~ mean_his, group_data)
# to have more details on the full test create a new object using the "=" symbol
lmhis = lm(mean_hes ~ mean_his, group_data)
summary(lmhis)
plot(lmhis)
summ(lmhis)
```

```{r LR black}
#to run the analysis without making it its own object and only having the beta coefficients 
lm(mean_hes ~ mean_black, group_data)
# to have more details on the full test create a new object using the "=" symbol
lmbl = lm(mean_hes ~ mean_black, group_data)
summary(lmbl)
plot(lmbl)
summ(lmbl)

lmbls = lm(mean_strong_hes ~ mean_black, group_data)
summary(lmbls)
plot(lmbls)
summ(lmbls)
```

```{r LR AI}
lm(mean_hes ~ mean_AI, group_data)
# to have more details on the full test create a new object using the "=" symbol
lmai = lm(mean_hes ~ mean_AI, group_data)
summary(lmai)
plot(lmai)
summ(lmai)

lmais = lm(mean_strong_hes ~ mean_AI, group_data)
summary(lmais)
plot(lmais)
summ(lmais)
```

```{r LR asian}
lm(mean_hes ~ mean_asian, group_data)
# to have more details on the full test create a new object using the "=" symbol
lmas = lm(mean_hes ~ mean_asian, group_data)
summary(lmas)
plot(lmas)
summ(lmas)

lmas_s = lm(mean_strong_hes ~ mean_asian, group_data)
summary(lmas_s)
plot(lmas_s)
summ(lmas_s)
```

```{r LR haw}
lm(mean_hes ~ mean_haw, group_data)
# to have more details on the full test create a new object using the "=" symbol
lmhaw = lm(mean_hes ~ mean_haw, group_data)
summary(lmhaw)
plot(lmhaw)
summ(lmhaw)

lmhaws = lm(mean_strong_hes ~ mean_haw, group_data)
summary(lmhaws)
plot(lmhaws)
summ(lmhaws)
```

```{r LR concern}
#to run the analysis without making it its own object and only having the beta coefficients 
lm(mean_hes ~ mean_concern, group_data)
# to have more details on the full test create a new object using the "=" symbol
lmcon = lm(mean_hes ~ mean_concern, group_data)
summary(lmcon)
plot(lmcon)
summ(lmcon)

lmcons = lm(mean_strong_hes ~ mean_concern, group_data)
summary(lmcons)
plot(lmcons)
summ(lmcons)
```

```{r concern vs. hes bar graph}
group_data %>%
  ggplot(aes(x=state, y=mean_concern, fill = pol)) + 
  geom_bar(stat="summary", fun="mean") +
 labs(title = "Avg. CVAC Level of Concern Per State", x = "State", y = "Avg. CVAC Level of Concern") +
  theme(legend.position = "none", plot.title = element_text(color = "darkred", size = 18, face = "bold"), axis.text.x = element_text(angle=90, vjust=1, hjust=1, size = 10)) +
  scale_fill_manual(values = c("darkblue", "red"))
```

```{r}
group_data %>%
  ggplot(aes(x=state, y=mean_concern, fill = hes_cat_2)) + 
  geom_bar(stat="summary", fun="mean") +
 labs(title = "Avg. CVAC Level of Concern Per State", x = NULL, y = "Avg. CVAC Level of Concern") +
  theme(legend.position = "bottom", plot.title = element_text(color = "coral2", size = 18, face = "bold"), axis.text.x = element_text(angle=90, vjust=1, hjust=1, size = 10)) +
  scale_fill_manual(values = c("darkgoldenrod1", "cyan4"))+ guides(fill=guide_legend(title="Hesitancy Cat."))
```

```{r hes}
ggplot(group_data, aes(mean_concern, mean_hes)) + geom_jitter(color = "darkseagreen") + geom_smooth(method="lm", formula = y ~ x,se=FALSE, col="coral1") +
  labs(title = "Avg. Hesitancy vs. Avg. CVAC Level of Concern", y = "Avg. Hesitancy", x = "Avg. Concern") +
  theme(plot.title = element_text(color = "cornflowerblue", size = 18, face = "bold")) 
```

```{r concern vs strong}
ggplot(group_data, aes(mean_concern, mean_strong_hes)) + geom_jitter(color = "darkseagreen") + geom_smooth(method="lm", formula = y ~ x,se=FALSE, col="coral1") +
  labs(title = "Avg. Strong Hesitancy vs. Avg. CVAC Level of Concern", y = "Avg. Hesitancy", x = "Avg. Concern") +
  theme(plot.title = element_text(color = "cornflowerblue", size = 18, face = "bold")) 
```

# Chi-Square Part

```{r adding red vs. blue & regions}
group_data$pol <- c("Red", "Red", "Blue", "Red", "Blue", "Blue", "Blue", "Blue", "Blue", "Red", "Blue", "Blue", "Red", "Blue", "Red", "Red", "Red", "Red", "Red", "Blue", "Blue", "Blue", "Blue", "Blue", "Red", "Red", "Red", "Red", "Blue", "Blue", "Blue", "Blue", "Blue", "Red", "Red", "Red", "Red", "Blue", "Blue", "Blue", "Red", "Red", "Red", "Red", "Red", "Blue", "Blue", "Blue", "Red", "Blue", "Red")

group_data$region <- c("S", "W", "W", "S", "W", "W", "NE", "S", "S", "S", "S", "W", "W", "MW", "MW", "MW", "MW", "S", "S", "NE", "S", "NE", "MW", "MW", "S", "MW", "W", "MW", "W", "NE", "NE", "W", "NE", "S", "MW", "MW", "S", "W", "NE", "NE", "S", "MW", "S", "S", "W", "NE", "S", "W", "S", "MW", "W")
view(group_data)
```

```{r splitting hes}
group_data$hes_cat<- cut(as.numeric(group_data$mean_hes),
                             breaks = quantile(as.numeric(group_data$mean_hes), probs = c(0, 1/3, 2/3, 1), na.rm = TRUE),
                             include.lowest = TRUE,
                             labels = c("Low", "Medium", "High"))
view(group_data)
```

```{r chi square pol vs. hes}
table(group_data$pol, group_data$hes_cat)

testpol<-fisher.test(group_data$pol,group_data$hes_cat, simulate.p.value = TRUE)
testpol
```

```{r pol vs. hes graph}
ggplot(group_data) +
  aes(x = pol, fill = hes_cat) +
  geom_bar(position = "dodge") +
  labs(title = "Vax. Hesitancy Red vs. Blue States", x = "State Political Color", y = "Count") +
  theme(plot.title = element_text(color = "darkgoldenrod3", size = 18, face = "bold"))+ guides(fill=guide_legend(title="Hes. Cat."))+ 
  scale_fill_manual(values = c("darkolivegreen", "cyan4", "darksalmon"))

```

```{r chi square region vs. hes}
table(group_data$region, group_data$hes_cat)

testreg<-fisher.test(group_data$region,group_data$hes_cat, simulate.p.value = TRUE)
testreg
```

```{r splitting hes just low vs. high}
group_data$hes_cat_2<- cut(as.numeric(group_data$mean_hes),
                             breaks = quantile(as.numeric(group_data$mean_hes), probs = c(0, 1/2, 1), na.rm = TRUE),
                             include.lowest = TRUE,
                             labels = c("Low", "High"))
view(group_data)
```

```{r chi square pol vs. hes lw}
table(group_data$pol, group_data$hes_cat_2)

testpol2<-chisq.test(group_data$pol,group_data$hes_cat_2)
testpol2
```

```{r pol vs. hes graph 2}
ggplot(group_data) +
  aes(x = pol, fill = hes_cat_2) +
  geom_bar(position = "dodge") +
  labs(title = "Vax. Hesitancy Red vs. Blue States", x = "State Political Color", y = "Count") +
  theme(plot.title = element_text(color = "darkgoldenrod3", size = 18, face = "bold"))+ guides(fill=guide_legend(title="Hes. Cat."))+ 
  scale_fill_manual(values = c("darkolivegreen", "darksalmon"))
```

```{r chi square pol vs. hes lw}
table(group_data$region, group_data$hes_cat_2)

testreg2<-fisher.test(group_data$region,group_data$hes_cat_2, simulate.p.value = TRUE)
testreg2
```

```{r region vs. hes graph 2}
ggplot(group_data) +
  aes(x = region, fill = hes_cat_2) +
  geom_bar(position = "dodge") +
  labs(title = "Vax. Hesitancy Per Region", x = "Region", y = "Count") +
  theme(plot.title = element_text(color = "darkgoldenrod3", size = 18, face = "bold"))+ guides(fill=guide_legend(title="Hes. Cat."))+ 
  scale_fill_manual(values = c("darkolivegreen", "darksalmon"))
```
